/*****************************************************************************
   data_api.h
   Generated By:
   Raptor 2022b_3.0.14889 (7266)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Nov 13 18:05:13 2024
 *****************************************************************************/

#ifndef DATA_API_H_
#define DATA_API_H_
#endif                                 /* DATA_API_H_ */
