/*****************************************************************************
   raptor_types.h
   Generated By:
   Raptor 2022b_3.0.14889 (7266)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Nov 13 18:05:13 2024
 *****************************************************************************/

#ifndef RAPTOR_TYPES_H
#define RAPTOR_TYPES_H
#include "rtwtypes.h"
#include "Accelerator_types.h"
#ifndef NULL
#define NULL                           (0)
#endif
#endif
