/*****************************************************************************
   time.h
   Generated By:
   Raptor 2022b_3.0.14889 (7266)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Nov 13 18:05:13 2024
 *****************************************************************************/

#ifndef TIME_H
#define TIME_H

uint32_T ticks(void);
uint32_T ticks_i(void);
uint32_T ticks_us(void);
uint32_T ticks_us_i(void);

#endif
